<?php
    require_once "conexion.php";
    //require_once "metodosCrud.php";
    $obj=new conectar();
    $conexion=$obj->conexion();
    $id=$_GET['id'];
    $sql="SELECT nombre,marca,modelo,color,capacidad
            from t_persona where id='$id'";
    $result=mysqli_query($conexion,$sql);
    $ver=mysqli_fetch_row($result);
?>
<html lang="en">
<head>
    <title>Document</title>
</head>
<body>
<form action="procesos/actualizar.php" method="post" >

        <input type="text" hidden="" value="<?php echo $id?>" name="id">
        <p></p>
        <label for="">Nombre</label>
        <p></p>
        <input type="text" name="txtnombre" value="<?php echo $ver[0]?>">
        <p></p>
        <label for="">Marca</label>
        <p></p>
        <input type="text" name="txtmarca" value="<?php echo $ver[1]?>">
        <p></p>
        <label for="">Modelo</label>
        <p></p>
        <input type="text" name="txtmodelo" value="<?php echo $ver[2]?>">
        <p></p>
        <label for="">Color</label>
        <p></p>
        <input type="text" name="txtcolor" value="<?php echo $ver[3]?>">
        <p></p>
        <label for="">Capacidad</label>
        <p></p>
        <input type="text" name="txtcapacidad" value="<?php echo $ver[4]?>">
        <p></p>
        
        <button>Actualizar</button>
    </form>
    
</body>
</html>